spring.application.name=mongo10web
spring.mongodb.host=localhost
spring.mongodb.port=27017
#spring.mongodb.username=admin
#spring.mongodb.password=123456
spring.mongodb.database=food_shop_storage
spring.mongodb.authentication-database=admin
spring.mongodb.auto-index-creation=false

spring.mongodb.custom.supplier-login=supplier
spring.mongodb.custom.supplier-password=123456
spring.mongodb.custom.storekeeper-login=storekeeper
spring.mongodb.custom.storekeeper-password=123456
spring.mongodb.custom.manager-login=manager
spring.mongodb.custom.manager-password=123456

server.port=8082



