spring:
  application:
    name: mongo10web
  mongodb:
    uri: mongodb://admin:123456@localhost:27017/new_sstu_database?authSource=admin
#    host: localhost
#    port: 27017
#    authentication-database: admin
#    username: admin
#    password: 123456
#    database: new_sstu_database
server:
  port: 8082